### ISSUE TITLE
How to preview Pictures or Videos?

### ISSUE THREAD

**Issue by unalozturk** [zhuozhuo/ZHChat#10]
I want to play video or show picture which is sent when I click to image or video. How can I implement it?

**Comment by zhuozhuo** [comment]
You can in the following judgments and actions in the interface.

``` objective-c
-(void)tableView:(ZHCMessagesTableView *)tableView didTapMessageBubbleAtIndexPath:(NSIndexPath *)indexPath
```

**Comment by unalozturk** [comment]
Thanks for reply but How i will know that message has picture or video?

**Comment by zhuozhuo** [comment]
You can be judged according to your custom message types, can also be judged according to the type of Item. For example:
```objective-c
if (message.isMediaMessage) {
        ZHCMediaItem *mediaItem = (ZHCMediaItem *)message.media;
        if ([mediaItem isKindOfClass:[ZHPhotoItem class]]) {
           //do something
        }
    }
```

**Comment by unalozturk** [comment]
Thanks a lot, it works like that perfectly 

` ZHCMessage *message = (ZHCMessage*)[self.demoData.messages objectAtIndex:indexPath.row ];
    if (message.isMediaMessage) {
        ZHCMediaItem *mediaItem = (ZHCMediaItem *)message.media;
        if ([mediaItem isKindOfClass:[ZHCPhotoMediaItem class]]) {
            NSLog(@"Picture");
        }
        if ([mediaItem isKindOfClass:[ZHCVideoMediaItem class]]) {
            NSLog(@"Video");    
        }
    }
`
