### ISSUE TITLE
Swift example can't scroll to bottom

### ISSUE THREAD

**Issue by deankai** [zhuozhuo/ZHChat#11]
as the title says, it's not worked

**Comment by deankai** [comment]
solve it already!self.scrollToBottom(animated: false); must be implemented in the viewDidAppear method

**Comment by zhuozhuo** [comment]
Hi, is the Swift Demo questions? ability to paste the following code, or Pull Request? I didn't see you said is a problem running.

**Comment by deankai** [comment]
HI 大神:
因為大家都是中國人，咱回中文您可別介意阿～
是這樣的～小弟剛開始學習聊天室開發，所以在看您的swift的example的時候，發現轉向不會自動轉畫面到最底下，
所以有這問題，不過後來解決了，只要和obj的example一樣在main thread處理就行，感謝您，
另外想請教就是，小弟因為初學聊天室，不知道該要如何學習呢？畢竟光是類就很多啊，建議您可以弄個教學文之類的，或是如果有問題，是否可以請教您呢？感謝！

2017-02-04 14:33 GMT+08:00 Mr.jiang <notifications@github.com>:

**Comment by zhuozhuo** [comment]
你上次回复的是否已经删除了，我只能看到一部分。关于用中文，在GitHub中尽量还是用英文描述吧，方便他人查看和提升自己的英文能力嘛。
