### ISSUE TITLE
How to get actual image or video from cell

### ISSUE THREAD

**Issue by zois** [zhuozhuo/ZHChat#13]
Hello,

can you please indicate a nice way on how to get e.g an UIImage from a ZHCPhotoMediaItem. I want to tap on a bubble and display the actual image. Currently, casting to NSData or UIImage fails.
Same for video. Someone would like to tap and play the actual video.
Just to say, I know how to get each type from the message. I am asking on how to use the "media" itself.

Thanks and keep up the very good work!

**Comment by zhuozhuo** [comment]
ZHChat Demo, like this:

```objective-c
-(void)tableView:(ZHCMessagesTableView *)tableView didTapMessageBubbleAtIndexPath:(NSIndexPath *)indexPath
{
    [super tableView:tableView didTapMessageBubbleAtIndexPath:indexPath];
    // Do something
    ZHCMessage *message = [self.demoData.messages objectAtIndex:indexPath.row];
    if (message.isMediaMessage) {
        if ([message.media isKindOfClass:[ZHCPhotoMediaItem class]]) {
            ZHCPhotoMediaItem *photoMedia = (ZHCPhotoMediaItem *)message.media;
            UIImage *img = photoMedia.image;
            NSLog(@"Photo");
        }else if ([message.media isKindOfClass:[ZHCVideoMediaItem class]]){
            ZHCVideoMediaItem *videoMedia = (ZHCVideoMediaItem *)message.media;
            NSURL *videoUrl = videoMedia.fileURL;
            NSLog(@"Video");
        }
    }
}

```

**Comment by zois** [comment]
Hi. This is not working in Swift. Both properties "image" and "fileURL" are not visible.
What I did is I got the image back with 
- UIImage(data: msg.media.mediaData!() as! Data)
And for the video I used the filename and got the url back from the documents folder, since I have already saved it there.

But I used to use JSQ library and indeed had these properties. 

Can you propose a solution for this in swift?

Thanks again!

**Comment by zois** [comment]
Actually my Xcode is not giving these properties. weird.
Never mind, I got them back by just writing them and it compiles!

let photoMedia:ZHCPhotoMediaItem = msg.media as! ZHCPhotoMediaItem
                let img:UIImage = photoMedia.image!

let videoMedia:ZHCVideoMediaItem = msg.media as! ZHCVideoMediaItem
                let vurl = videoMedia.fileURL

probably some issues with Xcode and swift3.
