### ISSUE TITLE
Disable emoji button and avatar image

### ISSUE THREAD

**Issue by hjy871** [zhuozhuo/ZHChat#15]
Hi, 

1. I can't seem to find a way to disable the emoji button on the toolbar. I've succeeded in removing the  voice and + button but not the emoji button. 

2. I've set nil for avatar image under the tableView:avatarImageDataForCellAtIndexPath method, but there is still the gap between the edge of the screen and the chat bubble. Is there a way to remove this?

Thank you

**Comment by zhuozhuo** [comment]
1. see [#9](https://github.com/zhuozhuo/ZHChat/issues/9) 
```objective-c
self.contentView.middleBarButtonItem = nil;
```
2. Added messageBubbleContainerView in ZHCMessagesTableViewCell width constraint and set to 0.

**Comment by hjy871** [comment]
Thank you so much!

Also, for item 2, I adjusted the following code because I can't seem to manipulate anything regarding the messageBubbleContainerView. 

```
 self.messageTableView.tableViewLayout.incomingAvatarViewSize = CGSizeMake(0, 30);
 self.messageTableView.tableViewLayout.outgoingAvatarViewSize = CGSizeMake(0, 30);
```
