### ISSUE TITLE
how to set incoming audio messages 

### ISSUE THREAD

**Issue by deankai** [zhuozhuo/ZHChat#16]
hi there, I have a question , now I have an incoming audio message(recoded voice), I use

`let audioItem: ZHCAudioMediaItem = ZHCAudioMediaItem.init(data: data);
        audioItem.appliesMediaViewMaskAsOutgoing = true;
        let audioMessage: ZHCMessage = ZHCMessage.init(senderId: self.senderId(), displayName: self.senderDisplayName(), media: audioItem);
        self.demoData.messages.add(audioMessage);
        self.finishSendingMessage(animated: true);`

this to display the voice message, but the point of the message is incorrect, how can I solve this problem?

**Comment by zhuozhuo** [comment]
Message is in or out based on message senderId and his same senderId to determine. Is the same whether it is into. So if someone else send message senderId cannot use when you initialize your senderId. The objectId of the sender can be used as message senderId。

For example:
```objective-c
audioItem.appliesMediaViewMaskAsOutgoing = false;
 let audioMessage: ZHCMessage = ZHCMessage.init(senderId:someoneId , displayName: someoneName, media: audioItem);
```

**Comment by deankai** [comment]
Thank u very much , unbelieved that ur answer  come so quickly.Thumb!
