### ISSUE TITLE
received voice message can't display correctly

### ISSUE THREAD

**Issue by deankai** [zhuozhuo/ZHChat#17]
<img width="167" alt="2017-03-21 4 26 24" src="https://cloud.githubusercontent.com/assets/25227326/24138440/28983d1c-0e53-11e7-896d-c997c550258f.png">

as the pic,after I received voice message,I'm sure that I get the correct data, and it can be played if I saved it in app's documents, but after I set like this

`let audioItem: ZHCAudioMediaItem = ZHCAudioMediaItem.init(data: audioData as Data);
        audioItem.appliesMediaViewMaskAsOutgoing = false
        let audioMessage: ZHCMessage = ZHCMessage.init(senderId: senderID, displayName: senderName, media: audioItem);
        self.demoData.messages.add(audioMessage);
        self.finishReceivingMessage(animated: true)`

it can't play ,just like the above pic, the time is zero, and can't be played , did I do anything wrong?

**Comment by zhuozhuo** [comment]
`AudioData` is to initialize the `audioItem` you have finished downloading it? If the `audioData` is empty it will not work. I suggest you create a class that inherits from `ZHCMediaItem`, add an initialized according to the address and voice interfaces. After downloading update `audioData` and cell interface in voice.

**Comment by deankai** [comment]
Now I am sure that I do have data to initialize it, the only problem is that the voice data come from the android device and the data is data.3gpp .in this case even if I initialize it with data, it still can't correctly display it. any suggestion?

**Comment by zhuozhuo** [comment]
Perhaps this audio format is not supported. You downloaded the audio, then played with AVAudioPlayer. If you can't play, only to go the next format change or let the Android format when uploading to Apple support.

[Apple Reference](https://developer.apple.com/library/content/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html#//apple_ref/doc/uid/TP40001862-CH210-TPXREF101)

**Comment by deankai** [comment]
problem solved. Thank u. I ask the android developer to send .aac

**Comment by GopiK14** [comment]
Please check this guys #61
