### ISSUE TITLE
Regarding audio stop

### ISSUE THREAD

**Issue by AmandeepSinghIos** [zhuozhuo/ZHChat#21]
when i am just play the audio, before pause i pop in another view controller its already running ..................How to pause that audio

**Comment by zhuozhuo** [comment]
You can refer to `ZHCAudioMediaItem` to write a class that inherits from `ZHCMediaItem` and add a method to pause playback.


```
- (void)stopPlay
{
    if (self.audioPlayer && self.audioPlayer.playing) {
        self.playButton.selected = NO;
        [self stopProgressTimer];
        [self.audioPlayer stop];
    }
}
```

**Comment by AmandeepSinghIos** [comment]
![screen shot 2017-04-07 at 3 51 44 pm](https://cloud.githubusercontent.com/assets/26954504/24796329/3126fc84-1baa-11e7-8b93-c315db78d0da.png)
this error is showing when i pop to another controller with ur latest code also........

**Comment by zhuozhuo** [comment]
This error is the release of the ProgressView after the pop operation, but the audio callback function calls the freed ProgressView. So you can follow the custom item I said above and add a pause method to pause playback of the audio before the pop operation.

**Comment by zhuozhuo** [comment]
The problem has just been repaired. You can download the latest Objective-c version of the test.
