### ISSUE TITLE
I want to completely remove ZHCMessagesInputToolbar empty space

### ISSUE THREAD

**Issue by imran233113** [zhuozhuo/ZHChat#26]
Hi , How to remove ZHCMessagesInputToolbar, so that i can use my own custom

**Comment by zhuozhuo** [comment]
If you want to remove `ZHCMessagesInputToolbar`, you can only modify the source code. You can fork the whole project and then modify `InputMessageBarView` in `ZHCMessagesViewController`. Of course, many other unforeseen problems may arise during the revision process, and if you are sure you want to modify it, you must understand the framework of the entire project.

**Comment by imran233113** [comment]
Thanks i made it done and once more thanks for wonderful library
