### ISSUE TITLE
How to set correct othersUserName and avater  image while group chat

### ISSUE THREAD

**Issue by web8246** [zhuozhuo/ZHChat#28]
Hi :
me again, I have a new problem , I know that use the func "avatarImageDataForCellAt" can set the correct avater. but my problem is how to set others name during the group chat by using the func"func othersJid() ->String" ?
thank u!

**Comment by web8246** [comment]
haha , sorry it's been too long I didn't use this 3rd party . I figure it out , all I need is set to correct ZHCMessage's senderDisplayName.

**Comment by zhuozhuo** [comment]
If your problem has been solved, you can manually close this issue.
