### ISSUE TITLE
Message Toolbar not showing above keyboard in the app with tabbar view controller.

### ISSUE THREAD

**Issue by vuevrn** [zhuozhuo/ZHChat#29]
Hello, I am using a tabbar view controller in my app. I am using your library for chat ui. It's working nicely. 

I have an issue. I am hiding tabbar with hidesbottombarwhenpushed when pushing into chat view controller, everything is fine except the when I click the textview in messagetoolbar, the toolbar won't show above the keyboard. 

Need help. 

Thank you.

**Comment by zhuozhuo** [comment]
Thank you very much for your feedback and has been repaired.
