### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by creatorpros** [zhuozhuo/ZHChat#3]
Hi, I really like ZHChat application, Previously I Tried it once that time its works fine and now Im try to import the entire framework into my new application It shows a error like this "" 256 duplicate symbols for architecture x86_64 ""

**Comment by zhuozhuo** [comment]
If you have an entire folder to import, delete and update in `Pods`. You can also try emptying the `DerivedData`. Maybe the answer may help you:(http://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64)

**Comment by creatorpros** [comment]
Thank You so much for your valuable response.
