### ISSUE TITLE
How to expand height of text view 

### ISSUE THREAD

**Issue by AmandeepSinghIos** [zhuozhuo/ZHChat#30]
![screen shot 2017-05-24 at 6 40 03 pm](https://cloud.githubusercontent.com/assets/26954504/26404790/c50df5ee-40b0-11e7-8d71-9fd60e656296.png)
After completion of the first line i want to expand the height of text view ......just like chat applications

**Comment by GopiK14** [comment]
Is this done? Any reference would be good?
