### ISSUE TITLE
How to implement the text of cell top label only

### ISSUE THREAD

**Issue by web8246** [zhuozhuo/ZHChat#34]
Hi there:
I now can change the text of the cell top label using
`override func tableView(_ tableView: ZHCMessagesTableView, attributedTextForCellTopLabelAt indexPath: IndexPath) -> NSAttributedString?`

but how can I implement this label's text only?like wechat?
![2017-06-27 1 30 33](https://user-images.githubusercontent.com/14540700/27573092-951f64d8-5b42-11e7-9765-f04de4598d35.png)

Thanks

**Comment by zhuozhuo** [comment]
What effect do you want? If you don't need a label to return nil in its corresponding method, it returns 0 in the height interface.

Like this：

```
override func tableView(_ tableView: ZHCMessagesTableView, attributedTextForCellTopLabelAt indexPath: IndexPath) -> NSAttributedString? {
        /**
         *  This logic should be consistent with what you return from `heightForCellTopLabelAtIndexPath:`
         *  The other label text delegate methods should follow a similar pattern.
         *
         *  Show a timestamp for every 3rd message
         */
        return nil;
        
    }

override func tableView(_ tableView: ZHCMessagesTableView, heightForCellTopLabelAt indexPath: IndexPath) -> CGFloat {
        /**
         *  Each label in a cell has a `height` delegate method that corresponds to its text dataSource method
         */
        
        /**
         *  This logic should be consistent with what you return from `attributedTextForCellTopLabelAtIndexPath:`
         *  The other label height delegate methods should follow similarly
         *
         *  Show a timestamp for every 3rd message
         */
        var labelHeight = 0.0;
        return CGFloat(labelHeight);
    }

```

**Comment by zhuozhuo** [comment]
You can refer to this interface architecture.

![2017-06-27 14 52 09](https://user-images.githubusercontent.com/4192811/27574520-524d069a-5b49-11e7-8941-f6c767ba6786.png)

**Comment by web8246** [comment]
I want the effect like wechat or Line
<img width="296" alt="2017-06-27 3 41 32" src="https://user-images.githubusercontent.com/14540700/27576325-3255f51c-5b4f-11e7-8a95-af178a8479f1.png">

u can see that if someone joint the room, this label shows , then it will tell other users that some body joined us, or below this label , means that u didn't read these messages yet.

Now I create a new ZHCMessage , and I do some changes ,then the Label will implement the text I hope it to show.
![2017-06-27 3 47 52](https://user-images.githubusercontent.com/14540700/27576576-07424e7e-5b50-11e7-9ae6-433f152a30a4.png)

However I can't dismiss the bubble or set the rest of the cell height = 0.
How can I do it? if I want to set the cell's main body height = 0?

**Comment by zhuozhuo** [comment]
Chat text information types can not be modified, if you want to modify only the source code. I suggest that you can customize the inheritance to `ZHCMediaItem` and follow the `ZHCMessageMediaData` view to show.
