### ISSUE TITLE
The text bubbles

### ISSUE THREAD

**Issue by devalios** [zhuozhuo/ZHChat#5]
The text bubbles can not be configured to do the full width should be?

Until then touch the bubble as the text if the text is short.
![buble](https://cloud.githubusercontent.com/assets/2991513/19919417/f5f0e9ec-a0d2-11e6-8a84-24aa6280cb96.png)

**Comment by zhuozhuo** [comment]
I think you can check whether the 'messageBubbleContainerView' constraint contains a width constraint.

**Comment by zhuozhuo** [comment]
Like this：
![2016-11-02 16 21 09](https://cloud.githubusercontent.com/assets/4192811/19921392/b0b9c240-a118-11e6-9ae4-5316f209f3ff.png)

**Comment by devalios** [comment]
I set up but has not narrowed the bubble :(

**Comment by zhuozhuo** [comment]
Do you use 'JSQMessagesViewController' or 'ZHChat' libraries?

**Comment by devalios** [comment]
ZHChat' libraries

**Comment by zhuozhuo** [comment]
Later, I take a look now.

**Comment by zhuozhuo** [comment]
You can use the 'diff' command in ZHChat under 'ZHCMessagesTableViewCell' and 'ZHCMessagesViewController' and differences of the same file in your project. I think it is most likely that when I said the width of the constraints that you changed.

**Comment by devalios** [comment]
The latest version of today

**Comment by devalios** [comment]
Can not you set the default project?

**Comment by zhuozhuo** [comment]
Not set by default, you need to manually specify the version. You copy the entire library to the project or use pods?

**Comment by devalios** [comment]
I do not use the pod.
Manually Install copier

**Comment by zhuozhuo** [comment]
If it is convenient, you can upload a Demo tomorrow if I have time during the day to help you see why.

**Comment by devalios** [comment]
I do not understand now.

Tomorrow I get a solution?

**Comment by zhuozhuo** [comment]
ok。Did you find the cause?

**Comment by devalios** [comment]
There is no solution?
To follow the text bubble?

**Comment by zhuozhuo** [comment]
Because you to customize the library, the best approach is to compare the front command do you use the two files I said or you labeled obtain highly code, I help you check!

**Comment by devalios** [comment]
Thanks,
You can not set ..
No, I will use this module :(

**Comment by appsyscode** [comment]
I see resolved
