### ISSUE TITLE
SWIFT Version ?

### ISSUE THREAD

**Issue by dipkasyap** [zhuozhuo/ZHChat#6]
Is it possible to provide swift version demo project please ?

**Comment by zhuozhuo** [comment]
Swift version of the Demo did not write, I found time to write a Swift Demo.

**Comment by dipkasyap** [comment]
Let me help, i wil write one !

**Comment by zhuozhuo** [comment]
Hi,Swift version of the Demo have been added.

**Comment by dipkasyap** [comment]
Thnks @zhuozhuo  :)
