### ISSUE TITLE
How to use online avatar image ?

### ISSUE THREAD

**Issue by Whirlwind** [zhuozhuo/ZHChat#8]
I don't find any API to download the image from a url. and I can't find any update avatar if I download the image by myself, too.

**Comment by zhuozhuo** [comment]
You can use the following functions for processing:
```objective-c
- (nullable id<ZHCMessageAvatarImageDataSource>)tableView:(ZHCMessagesTableView *)tableView avatarImageDataForCellAtIndexPath:(NSIndexPath *)indexPath
```
When you download avatar update interface.

**Comment by Whirlwind** [comment]
I use this function, but I think that it is not a good way. I must control the download manager and void to duplicate download, and update all table view when the download process is completed. 

I hope that there is a api to use the url string instead of a image object.

**Comment by zhuozhuo** [comment]
You can cache images locally and not every time you want to download. Or added one image URL in the ZHCMessagesTableViewCell interface, but the principle is still the same, you need to cache the updated interface.
