### ISSUE TITLE
How to disable `voice` button and `+` button?

### ISSUE THREAD

**Issue by Whirlwind** [zhuozhuo/ZHChat#9]
I want not to show the left button and right button, just a textview and emoji view. I can't find the api to hide them. Please tell me if I miss it.

**Comment by zhuozhuo** [comment]
You need to define ZHCMessagesToolbarContentView and ZHCMessagesInputToolbar. In ZHCMessagesToolbarContentView, you need to delete unwanted views, and make the changes in the ZHCMessagesInputToolbar.

**Comment by Whirlwind** [comment]
I use this code:
```
    self.inputMessageBarView.contentView.leftBarButtonItem = nil;
    self.inputMessageBarView.contentView.rightBarButtonItem = nil;
```
They are OK. but they is too hard to find it. :(

**Comment by zhuozhuo** [comment]
You can modify after the test.
